### ISSUE TITLE
Your configuration files are not serializable

### ISSUE THREAD

**Issue by qurbanullah** [rahulalam31/Laravel-Abuse-IP#11]
While executing the command: 

php artisan config:cache

Following error occurred.

   LogicException 

  Your configuration files are not serializable.

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:73
     69▕             require $configPath;
     70▕         } catch (Throwable $e) {
     71▕             $this->files->delete($configPath);
     72▕ 
  ➜  73▕             throw new LogicException('Your configuration files are not serializable.', 0, $e);
     74▕         }
     75▕ 
     76▕         $this->components->info('Configuration cached successfully.');
     77▕     }

  1   bootstrap/cache/config.php:9
      Error::("Call to undefined method Closure::__set_state()")
      +13 vendor frames 

  15  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
      
      
      
This error is due to the closure function used in config file (abuseip.php).

Work around is to move the closure to the Middlerware (AbuseIp.php).

**Comment by EriBloo** [comment]
It seems you have an old version of package installed. This was fixed in 1.3.

**Comment by qurbanullah** [comment]
Sorry and Thanks. But I did not pass any version while installing. I believe that latest one might have been installed. But version 1.2 was installed by default.
