### ISSUE TITLE
Doesn't work with database driver for caching

### ISSUE THREAD

**Issue by csoutham** [rahulalam31/Laravel-Abuse-IP#6]
When running `php artisan abuseip:update` with the database driver enabled for caching, it throws an error `... on duplicate key update 'expiration' = values('expiration'), 'key' = values('key'), 'value' = values('value'))` which is related to the `Cache::forever('abuse_ips', $ips);` command.

Using redis/predis or file as the cache driver works without failure, but the database driver is now the default in Laravel 11.

Fantastic idea for a package, really worth while - thank you!

**Comment by EriBloo** [comment]
Reason for this error is that, by default, Laravel cache migration creates `value` column of type `MEDIUMTEXT`, but ip list is so long it doesn't fit. Changing column to `LONGTEXT` fixes this issue.

**Comment by csoutham** [comment]
Nice one, great answer - have tested and you are absolutely right!
