### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by kirkaracha** [rahulalam31/Laravel-Abuse-IP#9]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes) in vendor/rahulalam31/laravel-abuse-ip/src/Console/Commands/UpdateAbuseIps.php on line 47

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in vendor/laravel/framework/src/Illuminate/Session/Store.php on line 489

**Comment by EriBloo** [comment]
Hi. Are you using default config or added additional sources?

**Comment by dimer47** [comment]
Hello,
I'm experiencing the same issue on my side, both in my unit tests and functional tests. When I run the full test suite, this error consistently appears. From what I can tell, it seems more related to the functional tests.

What puzzles me is that, even though my test URLs are supposed to go through the middleware (based on the configuration), when I add dd() calls inside the middleware, they are never hit. This makes me think the middleware isn't actually being triggered, yet the error still occurs. 

For context, I'm using Docker with a Laravel Sail-based development environment. I'm happy to provide more details or share example code if that helps.

Have you identified any potential causes for this behavior?
